### ISSUE TITLE
Missing fclose in position_index.c

### ISSUE THREAD

**Issue by FlorianW-ZAMG** [harphub/Rgrib2#5]
Hi,

there is a `fclose(infile);` statement missing in position_index.c
The infile is opened but not closed at the end of the routine. This can cause problems when running the the grib-extraction for multiple parameter or long periods, since there is an increasing number of open files that are never closed.

Best regards,
Florian

**Comment by adeckmyn** [comment]
You are right. Thanks for finding and reporting this. I'll fix it asap.

**Comment by adeckmyn** [comment]
Fixed. Thanks.
